version: '3.9'

services:
  secret-letters:
    container_name: secret-letters-app
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - 'redis'
    depends_on:
      - redis
    restart: on-failure
    environment:
      - LOCAL="true"
      - PORT=8080
      - REDIS_URL=redis
      - SECRET_KEY=abcdefghijklmnopqrstuvwxyzawqerz
    ports:
      - '8080:8080'
  redis:
    container_name: secret-letters-db
    image: redis
    restart: on-failure
